# General
graphQLEndpoint=https://portal.ehri-project.eu/api/graphql
querySparqlEndpoint=http://localhost:3030/ehri/query
updateSparqlEndpoint=http://localhost:3030/ehri/update
insertSparqlQuery=conf/sparqlInsertData.rq
eventDetailsSparqlQuery=conf/sparqlGetEventDetails.rq
resumeFromEventId=
# Overrides the STREAM URL of the SSE mapping rules when set
sseEndpoint=

# Database
databasePath=db/eventsHistory.db
databaseCreationScript=db/creation.sql

# Institutions
institutionsGraphQLQuery=conf/institutions/institutionsGraphQLQuery.txt
institutionsShexmlMappingRules=conf/institutions/institutionsMappingRules.shexml
institutionsDeleteSparqlQuery=conf/institutions/sparqlDeleteInstitutionData.rq
institutionsConstructSparqlQuery=conf/institutions/institutionsSparqlConstruct.rq

# Countries
countriesGraphQLQuery=conf/countries/countriesGraphQLQuery.txt
countriesShexmlMappingRules=conf/countries/countriesMappingRules.shexml
countriesDeleteSparqlQuery=conf/countries/sparqlDeleteCountryData.rq
countriesConstructSparqlQuery=conf/countries/countriesSparqlConstruct.rq

# Archival descriptions
archivalDescriptionsGraphQLQuery=conf/archivalDescriptions/archivalDescriptionsGraphQLQuery.txt
archivalDescriptionsShexmlMappingRules=conf/archivalDescriptions/archivalDescriptionsMappingRules.shexml
archivalDescriptionsDeleteSparqlQuery=conf/archivalDescriptions/sparqlDeleteArchivalDescriptionData.rq
archivalDescriptionsConstructSparqlQuery=conf/archivalDescriptions/archivalDescriptionsSparqlConstruct.rq

# Vocabularies
vocabulariesGraphQLQuery=conf/vocabularies/vocabulariesGraphQLQuery.txt
vocabulariesShexmlMappingRules=conf/vocabularies/vocabulariesMappingRules.shexml
vocabulariesDeleteSparqlQuery=conf/vocabularies/sparqlDeleteVocabularyData.rq
vocabulariesConstructSparqlQuery=conf/vocabularies/vocabulariesSparqlConstruct.rq

# Historical agents
historicalAgentsGraphQLQuery=conf/historicalAgents/historicalAgentsGraphQLQuery.txt
corporateBodiesShexmlMappingRules=conf/historicalAgents/corporateBodiesMappingRules.shexml
personsShexmlMappingRules=conf/historicalAgents/personsMappingRules.shexml
historicalAgentsDeleteSparqlQuery=conf/historicalAgents/sparqlDeleteHistoricalAgentData.rq
historicalAgentsConstructSparqlQuery=conf/historicalAgents/historicalAgentsSparqlConstruct.rq

# Links
linksGraphQLQuery=conf/links/linksGraphQLQuery.txt
linksShexmlMappingRules=conf/links/linksMappingRules.shexml
linksDeleteSparqlQuery=conf/links/sparqlDeleteLinkData.rq
linksConstructSparqlQuery=conf/links/linksSparqlConstruct.rq