PREFIX : <http://example.com/>

SELECT ?eventId ?eventType ?date ?ids ?types WHERE {
    ?event a :Event ;
        :eventType ?eventType ;
        :date ?date ;
        :hasTypedIds [
            a :TypedId ;
            :id ?ids ;
            :type ?types
        ] .
    BIND(STRAFTER(STR(?event), STR(:)) AS ?eventId)
}
